GET http://localhost:3000/movies 

###

GET http://localhost:3000/movies/241bf55d-b649-4109-af7c-0e6890ded3fc


###

GET http://localhost:3000/movies?genre=action

###

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"]
}

###
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 2022
}